steps:
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "gcr.io/inlaid-oasis-227305/eng-metrics", '.']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/eng-metrics', 'eng-metrics=gcr.io/inlaid-oasis-227305/eng-metrics']
